### ISSUE TITLE
run

### ISSUE THREAD

**Issue by ycx15514363536** [webfansplz/vuejs-challenges#1058]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

Basic info of your challenge questions,

```yaml
difficulty: easy # medium / hard / extreme
title: Your Question Name
tags: Directvies, Components # separate by comma
```

## Question

Describe and explain your question here. 

## Template

This is the template for challengers to start the coding. 

If you want to commit multiple files, just create multiple blocks and identify the file name and code block

filename: App.vue

```vue

```
