### ISSUE TITLE
依赖注入

### ISSUE THREAD

**Issue by webfansplz** [webfansplz/vuejs-challenges#12]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: easy

# 题目标题
title: 依赖注入

# 题目标签
tags: Composition API
```

## 题目模版

以下是给予挑战者开始做题的代码模版，

如果您想提交多个文件，只需创建多个`<!--challenges-start--><!--challenges-end-->`，并描述文件名和代码內容

filename: App.vue

```vue
<script setup lang="ts">
import { ref, provide } from "vue"
import Child from "./Child.vue"
const count = ref(1)
provide("count", count)
setInterval(() => {
  count.value++
}, 1000)
</script>

<template>
  <Child />
</template>

```

filename: Child.vue

```vue
<script setup lang="ts">
// Add code to make the `count` value injected into the child component.
</script>

<template>
  {{ count }}
</template>

```
