### ISSUE TITLE
 How do we use the scope slot?

### ISSUE THREAD

**Issue by PoliWen** [webfansplz/vuejs-challenges#1375]
> Please follow the template and fill the info. A PR will be auto-generated and always reflect on your changes.
>
> Detailed solution/guide is not required, but please be sure the challenge is solvable.

## Info

 How do we use the scope slot?

```yaml
difficulty: easy
title:How do we access the state of the child component when we use the slot
tags: Slots
```

## Question

In some cases, we need to get the child component's data from the parent component through the slot.
How do we use the scope slot?

## Template

filename: MyComponent .vue

```
<div>
  <slot :text="greetingMessage" :count="1"></slot>
</div>

```

filename: App.vue
```
<MyComponent v-slot="slotProps">
  {{ slotProps.text }} {{ slotProps.count }}
</MyComponent>

```
