### ISSUE TITLE
vue+element后台管理系统，列表接口在created调用，为什么切换时有的页面没有调用接口，而有的页面调用接口了

### ISSUE THREAD

**Issue by cl4u** [webfansplz/vuejs-challenges#187]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: easy # medium / hard / extreme

# 题目标题
title: 你的题目

# 题目标签
tags: union, array # separate by comma
```

## 题目

在这里描述并说明你的题目。

## 题目模版

以下是给予挑战者开始做题的代码模版，

如果您想提交多个文件，只需创建多个`<!--challenges-start--><!--challenges-end-->`，并按照以下格式填写文件名和代码內容

filename: App.vue

```vue

```
