### ISSUE TITLE
Capitalize

### ISSUE THREAD

**Issue by heappynd** [webfansplz/vuejs-challenges#205]
## Info

Basic info of your challenge questions,

```yaml
difficulty: easy
title: Capitalize
tags: Modifier
```

## Question

Please create a custom modifier `capitalize`, that capitalizes the first letter of the string provided by the v-model binding.

## Template

This is the template for challengers to start the coding. 

filename: App.vue

```vue
<script setup>
</script>

<template>
  <input type="text" v-model.capitalize="" />
</template>
```
