### ISSUE TITLE
Capitalize

### ISSUE THREAD

**Issue by heappynd** [webfansplz/vuejs-challenges#208]
## 基本信息

```yaml
# 题目难度
difficulty: easy

# 题目标题
title: Capitalize

# 题目标签
tags: Modifiers
```

## 题目

请创建一个自定义的修饰符 capitalize，它会自动将 v-model 绑定输入的字符串值第一个字母转为大写。

## 题目模版

以下是给予挑战者开始做题的代码模版，

filename: App.vue

```vue
<script setup>
</script>

<template>
  <input type="text" v-model.capitalize="" />
</template>
```
