### ISSUE TITLE
全局异常处理

### ISSUE THREAD

**Issue by murongg** [webfansplz/vuejs-challenges#262]
## 基本信息

```yaml
# 题目难度
difficulty: easy

# 题目标题
title: 全局异常处理

# 题目标签
tags: Event Handling
```

## 题目

在这个挑战中，你需要捕获到所有组件中的错误，并使组件正常渲染，让我们开始吧。

```vue
<script setup lang="ts">
throw new Error('error')
</script>

<template>
</template>
```

## 题目模版

以下是给予挑战者开始做题的代码模版，

如果您想提交多个文件，只需创建多个`<!--challenges-start--><!--challenges-end-->`，并按照以下格式填写文件名和代码內容

filename: main.ts

```ts
import { createApp } from 'vue'
import App from './App.vue'

createApp(App)
```

filename: App.vue

```vue
<script setup lang="ts">
throw new Error('error')
</script>

<template>
</template>
```
