### ISSUE TITLE
1111-hello-world

### ISSUE THREAD

**Issue by webfansplz** [webfansplz/vuejs-challenges#6]
> 请按照以下的模版填充相应的内容，一个 PR 会自动生成并保持与本 Issue 的内容同步。

> 你不需要提供详细的答案或教学，但请保证题目可解。

## 基本信息

```yaml
# 题目难度
difficulty: easy

# 题目标题
title: hello-world

# 题目标签
tags: Components # separate by comma
```

## 题目模版

以下是给予挑战者开始做题的代码模版，

如果您想提交多个文件，只需创建多个`<!--challenges-start--><!--challenges-end-->`，并描述文件名和代码內容

filename: App.vue

```vue
<script setup lang='ts'>
import { ref } from "vue"

const count = ref(0)

/**
 * Implement the until function
*/

function until(initial) {
  function toBe(value) {

  }

  return {
    toBe,
  }
}

async function increase() {
  count.value = 0
  setInterval(() => {
    count.value++
  }, 1000)
  await until(count).toBe(3)
  console.log(count.value === 3) // Make sure the output to be true
}

</script>

<template>
  <p @click="increase">
    Increase
  </p>
</template>

```
